CREATE DATABASE IF NOT EXISTS ${CLICKHOUSE_ETL_DATABASE};

CREATE TABLE IF NOT EXISTS ${CLICKHOUSE_ETL_DATABASE}.{{.Table}}
(

    {{.FieldsWTypes}}

    ) ENGINE = Null;

CREATE MATERIALIZED VIEW IF NOT EXISTS${CLICKHOUSE_ETL_DATABASE}.mv_to_{{.Table}}_rt TO ${CLICKHOUSE_RT_DATABASE}.{{.Table}}
AS SELECT

    {{.Fields}}

FROM ${CLICKHOUSE_ETL_DATABASE}.{{.Table}};